#!/usr/bin/env python3
"""Write the asset manifest: every screenshot, where it appears, and how.

Reads the generated pages rather than the sources, because what a visitor is
served is the only thing that settles which file is loaded eagerly, what its
responsive set is, and which view transition carries it into the next page.

    python3 tools/asset_manifest.py > artifacts/cinematic-overhaul/asset-manifest.md
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
IMG = re.compile(r"<img\b[^>]*>", re.S)
ATTR = re.compile(r'(\w[\w-]*)="([^"]*)"', re.S)


def section_for(html: str, at: int) -> str:
    """The nearest enclosing landmark, read backwards from the tag."""
    head = html[:at]
    for pattern, label in (
        (r'<section[^>]*aria-label(?:ledby)?="([^"]+)"', "section"),
        (r'<figure[^>]*class="([^"]+)"', "figure"),
    ):
        found = re.findall(pattern, head)
        if found:
            return found[-1]
    return "—"


def main() -> int:
    rows = []
    used: set[str] = set()
    for page in sorted(ROOT.glob("*.html")):
        html = page.read_text(encoding="utf-8")
        for m in IMG.finditer(html):
            a = dict(ATTR.findall(m.group(0)))
            src = a.get("src", "")
            if not src.startswith("assets/"):
                continue
            variants = re.findall(r"(assets/[^\s,\"]+\.webp)\s+(\d+)w", a.get("srcset", ""))
            for v, _ in variants:
                used.add(v)
            used.add(src)
            rows.append(
                {
                    "page": page.name,
                    "where": section_for(html, m.start()),
                    "file": src,
                    "intrinsic": f'{a.get("width","?")}×{a.get("height","?")}',
                    "variants": ", ".join(f"{w}w" for _, w in variants) or "—",
                    "sizes": a.get("sizes", "—"),
                    "loading": ("eager, fetchpriority high" if a.get("loading") == "eager" else "lazy"),
                    "vt": a.get("data-vt", "—"),
                    "alt": a.get("alt", ""),
                }
            )

    print("# Asset manifest\n")
    print(
        "Every screenshot the site serves, the page and section it appears in, its\n"
        "intrinsic size, the responsive derivatives generated from it, whether it is\n"
        "the page's LCP candidate or lazy, and the view-transition name it carries\n"
        "into the next document.\n"
    )
    print("Generated by `python3 tools/asset_manifest.py` from the committed HTML.\n")

    for page in sorted({r["page"] for r in rows}):
        group = [r for r in rows if r["page"] == page]
        print(f"## `{page}`\n")
        print("| File | Section | Intrinsic | Variants | `sizes` | Loading | View transition |")
        print("| --- | --- | --- | --- | --- | --- | --- |")
        for r in group:
            print(
                f'| `{r["file"].replace("assets/projects/","")}` | {r["where"]} | {r["intrinsic"]} | '
                f'{r["variants"]} | `{r["sizes"]}` | {r["loading"]} | `{r["vt"]}` |'
            )
        print()
        for r in group:
            print(f'- **alt** — `{r["file"].split("/")[-1]}`: {r["alt"]}')
        print()

    # Anything in assets/projects that no page serves.
    on_disk = {
        str(p.relative_to(ROOT)) for p in (ROOT / "assets" / "projects").rglob("*.webp")
    }
    unused = sorted(on_disk - used)
    originals = [u for u in unused if not re.search(r"-\d+\.webp$", u)]
    derivatives = [u for u in unused if re.search(r"-\d+\.webp$", u)]

    print("## Files no page currently serves\n")
    if originals:
        print("### Originals\n")
        print(
            "Captures of the real products that the current layout does not place.\n"
            "They are kept rather than deleted: each one is a capture of a running\n"
            "build that cannot be re-taken from this repository, and each is evidence\n"
            "behind a claim its case study makes in prose. Deleting them would cost\n"
            "the record and save a few kilobytes that no visitor downloads.\n"
        )
        for u in originals:
            print(f"- `{u}`")
        print()
    if derivatives:
        print("### Unplaced derivatives\n")
        print(
            "`tools/build_images.mjs` writes a 720 px and a 1280 px rendition of every\n"
            "original, so a derivative of an unplaced original is unplaced too. They\n"
            "are regenerated from the originals and are safe to remove at any time.\n"
        )
        for u in derivatives:
            print(f"- `{u}`")
        print()
    if not unused:
        print("None — every file in `assets/projects/` is served by at least one page.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
